import 'dart:async';

// `hide AuthProvider`: firebase_auth's own package exports a class called AuthProvider (the
// base type behind EmailAuthProvider/GoogleAuthProvider/etc.) which collides with our app's own
// AuthProvider (features/auth/auth_provider.dart, our login/session state) — hiding theirs since
// we never use it directly here, only FirebaseAuth.instance itself.
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

import 'core/api_client.dart';
import 'core/router.dart';
import 'core/theme.dart';
import 'features/auth/auth_provider.dart';
import 'features/catalog/catalog_provider.dart';
import 'features/catalog/catalog_service.dart';
import 'features/notifications/notification_service.dart';
import 'features/orders/orders_provider.dart';
import 'features/orders/orders_service.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase requires real project credentials (lib/firebase_options.dart +
  // android/app/google-services.json), generated by running `flutterfire configure`.
  // Until that's done, DefaultFirebaseOptions.currentPlatform holds placeholder values and
  // Firebase.initializeApp() throws. Previously that exception happened before runApp(), so
  // Flutter never got to draw a single frame — hence the black screen on launch. We catch
  // that failure, skip Firebase-dependent setup, and still show the UI (with a banner) so the
  // app opens and tells you what's missing instead of just going black.
  //
  // Separately, once google-services.json IS in place, the google-services Gradle plugin makes
  // the native Firebase SDK auto-initialize a "[DEFAULT]" app before Dart code ever runs — even
  // on a fresh cold start, before Firebase.apps (Dart-side) knows about it. Calling
  // initializeApp() from Dart then throws core/duplicate-app; that's expected in that case (the
  // native default app is already configured correctly) and does NOT mean Firebase isn't ready.
  var firebaseReady = true;
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } on FirebaseException catch (e) {
    if (e.code != 'duplicate-app') {
      firebaseReady = false;
      debugPrint('Firebase.initializeApp failed — run `flutterfire configure` to fix. Error: $e');
    }
  } catch (e) {
    firebaseReady = false;
    debugPrint('Firebase.initializeApp failed — run `flutterfire configure` to fix. Error: $e');
  }

  if (firebaseReady) {
    // Must be registered before runApp so Android can wake this isolate for a push that arrives
    // while the app is fully closed.
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  }

  final apiClient = ApiClient(
    tokenProvider: () =>
        firebaseReady ? (FirebaseAuth.instance.currentUser?.getIdToken() ?? Future.value(null)) : Future.value(null),
  );
  final notificationService = NotificationService(apiClient);

  // Paint the app immediately instead of awaiting this — on Android 13+, init() blocks on the
  // system notification-permission dialog (_messaging.requestPermission), and if that dialog is
  // slow to render (or the screen was off/locked at cold start), the user was stuck staring at
  // the bare native splash background indefinitely with nothing ever drawn. Firing it after
  // runApp() means the real UI is already visible underneath whenever that dialog does appear.
  runApp(Store8AdminApp(
    apiClient: apiClient,
    notificationService: notificationService,
    firebaseReady: firebaseReady,
  ));
  if (firebaseReady) {
    unawaited(notificationService.init());
  }
}

class Store8AdminApp extends StatefulWidget {
  final ApiClient apiClient;
  final NotificationService notificationService;
  final bool firebaseReady;
  const Store8AdminApp({
    super.key,
    required this.apiClient,
    required this.notificationService,
    required this.firebaseReady,
  });

  @override
  State<Store8AdminApp> createState() => _Store8AdminAppState();
}

class _Store8AdminAppState extends State<Store8AdminApp> {
  AuthProvider? _authProvider;
  GoRouter? _router;

  @override
  void initState() {
    super.initState();
    // AuthProvider's constructor touches FirebaseAuth.instance, which throws if Firebase never
    // initialized (see main()). Only build the real app (auth/router/providers) when Firebase is
    // actually ready; otherwise fall through to the setup-needed screen below instead of crashing
    // again here.
    if (!widget.firebaseReady) return;

    _authProvider = AuthProvider(widget.apiClient, widget.notificationService);
    _router = buildRouter(_authProvider!);

    // A tapped notification can arrive before auth/redirect has settled (cold start). A short
    // delay lets GoRouter finish its initial /splash -> /dashboard redirect first, then we push
    // the order on top — simple and reliable for this app's scale.
    widget.notificationService.onOrderTapped = (orderId) {
      Future.delayed(const Duration(milliseconds: 350), () => _router!.push('/orders/$orderId'));
    };
  }

  @override
  Widget build(BuildContext context) {
    if (!widget.firebaseReady) {
      // Firebase isn't configured yet (run `flutterfire configure` from gym-app/store8, see
      // lib/firebase_options.dart). Showing this instead of a black screen so the app is at
      // least visibly alive and tells you what to do next.
      return const MaterialApp(
        debugShowCheckedModeBanner: false,
        home: _FirebaseSetupNeededScreen(),
      );
    }

    return MultiProvider(
      providers: [
        Provider.value(value: widget.apiClient),
        Provider.value(value: widget.notificationService),
        Provider(create: (_) => CatalogService(widget.apiClient)),
        Provider(create: (_) => OrdersService(widget.apiClient)),
        ChangeNotifierProvider.value(value: _authProvider!),
        ChangeNotifierProvider(create: (ctx) => CatalogProvider(ctx.read<CatalogService>())),
        ChangeNotifierProvider(create: (ctx) => OrdersProvider(ctx.read<OrdersService>())),
      ],
      child: MaterialApp.router(
        title: 'Store 8 Admin',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.dark,
        darkTheme: AppTheme.dark,
        themeMode: ThemeMode.dark,
        routerConfig: _router!,
      ),
    );
  }
}

class _FirebaseSetupNeededScreen extends StatelessWidget {
  const _FirebaseSetupNeededScreen();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF111111),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.warning_amber_rounded, color: Colors.amber, size: 48),
              const SizedBox(height: 16),
              const Text(
                'Firebase is not set up yet',
                style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 12),
              const Text(
                'Run this from gym-app/store8 on your computer, then rebuild the app:\n\n'
                'flutterfire configure --project=<your-firebase-project-id>',
                style: TextStyle(color: Colors.white70, fontSize: 14, height: 1.5),
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
